// Auto-generated by scripts/build-projekte.js — do not edit by hand.
// Source: markdown files in _projekte/, managed via /admin (Decap CMS).

const PROJEKTE = [
  {
    "id": "projekt-01",
    "projekt": "Maastrichter Straße",
    "massstab": "1:200",
    "kunde": "Studierende",
    "format": "quer",
    "titelbild": "/images/projekte/8c4d4d7d-3216-40d1-923c-6bb9b06abe7d.jpg",
    "weitereBilder": [
      "/images/projekte/081828b6-fb2d-4ae0-a707-27920fc0a6d5.jpg",
      "/images/projekte/a02f6997-3ab6-4e55-8b23-f1eb133b83c3.jpg",
      "/images/projekte/b05da660-d9f6-4a1a-bdc7-3a5360d9d919.jpg",
      "/images/projekte/b51b2498-cc7c-47b7-80b7-87f3e3cbd729.jpg",
      "/images/projekte/cf0e24df-4d53-440c-8935-8c89a5392f0b.jpg"
    ]
  },
  {
    "id": "projekt-02",
    "projekt": "Projekt 02",
    "massstab": "1:50",
    "kunde": "Privat",
    "format": "hoch",
    "titelbild": "images/platzhalter/projekt-02-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-02-a.jpg",
      "images/platzhalter/projekt-02-b.jpg",
      "images/platzhalter/projekt-02-c.jpg",
      "images/platzhalter/projekt-02-d.jpg"
    ]
  },
  {
    "id": "projekt-03",
    "projekt": "Projekt 03",
    "massstab": "1:200",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-03-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-03-a.jpg",
      "images/platzhalter/projekt-03-b.jpg",
      "images/platzhalter/projekt-03-c.jpg"
    ]
  },
  {
    "id": "projekt-04",
    "projekt": "Projekt 04",
    "massstab": "1:100",
    "kunde": "Privat",
    "format": "quadrat",
    "titelbild": "images/platzhalter/projekt-04-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-04-a.jpg",
      "images/platzhalter/projekt-04-b.jpg",
      "images/platzhalter/projekt-04-c.jpg",
      "images/platzhalter/projekt-04-d.jpg"
    ]
  },
  {
    "id": "projekt-05",
    "projekt": "Projekt 05",
    "massstab": "1:100",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-05-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-05-a.jpg",
      "images/platzhalter/projekt-05-b.jpg",
      "images/platzhalter/projekt-05-c.jpg"
    ]
  },
  {
    "id": "projekt-06",
    "projekt": "Projekt 06",
    "massstab": "1:50",
    "kunde": "Privat",
    "format": "quadrat",
    "titelbild": "images/platzhalter/projekt-06-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-06-a.jpg",
      "images/platzhalter/projekt-06-b.jpg",
      "images/platzhalter/projekt-06-c.jpg",
      "images/platzhalter/projekt-06-d.jpg"
    ]
  },
  {
    "id": "projekt-07",
    "projekt": "Projekt 07",
    "massstab": "1:200",
    "kunde": "Privat",
    "format": "hoch",
    "titelbild": "images/platzhalter/projekt-07-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-07-a.jpg",
      "images/platzhalter/projekt-07-b.jpg",
      "images/platzhalter/projekt-07-c.jpg"
    ]
  },
  {
    "id": "projekt-08",
    "projekt": "Projekt 08",
    "massstab": "1:100",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-08-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-08-a.jpg",
      "images/platzhalter/projekt-08-b.jpg",
      "images/platzhalter/projekt-08-c.jpg"
    ]
  }
];

window.PROJEKTE = PROJEKTE;
