// Auto-generated by scripts/build-projekte.js — do not edit by hand.
// Source: markdown files in _projekte/, managed via /admin (Decap CMS).

const PROJEKTE = [
  {
    "id": "projekt-01",
    "projekt": "Projekt 01",
    "massstab": "1:100",
    "kunde": "Privat",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-01-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-01-a.jpg",
      "images/platzhalter/projekt-01-b.jpg",
      "images/platzhalter/projekt-01-c.jpg"
    ]
  },
  {
    "id": "projekt-02",
    "projekt": "Projekt 02",
    "massstab": "1:50",
    "kunde": "Privat",
    "format": "hoch",
    "titelbild": "images/platzhalter/projekt-02-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-02-a.jpg",
      "images/platzhalter/projekt-02-b.jpg",
      "images/platzhalter/projekt-02-c.jpg",
      "images/platzhalter/projekt-02-d.jpg"
    ]
  },
  {
    "id": "projekt-03",
    "projekt": "Projekt 03",
    "massstab": "1:200",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-03-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-03-a.jpg",
      "images/platzhalter/projekt-03-b.jpg",
      "images/platzhalter/projekt-03-c.jpg"
    ]
  },
  {
    "id": "projekt-04",
    "projekt": "Projekt 04",
    "massstab": "1:100",
    "kunde": "Privat",
    "format": "quadrat",
    "titelbild": "images/platzhalter/projekt-04-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-04-a.jpg",
      "images/platzhalter/projekt-04-b.jpg",
      "images/platzhalter/projekt-04-c.jpg",
      "images/platzhalter/projekt-04-d.jpg"
    ]
  },
  {
    "id": "projekt-05",
    "projekt": "Projekt 05",
    "massstab": "1:100",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-05-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-05-a.jpg",
      "images/platzhalter/projekt-05-b.jpg",
      "images/platzhalter/projekt-05-c.jpg"
    ]
  },
  {
    "id": "projekt-06",
    "projekt": "Projekt 06",
    "massstab": "1:50",
    "kunde": "Privat",
    "format": "quadrat",
    "titelbild": "images/platzhalter/projekt-06-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-06-a.jpg",
      "images/platzhalter/projekt-06-b.jpg",
      "images/platzhalter/projekt-06-c.jpg",
      "images/platzhalter/projekt-06-d.jpg"
    ]
  },
  {
    "id": "projekt-07",
    "projekt": "Projekt 07",
    "massstab": "1:200",
    "kunde": "Privat",
    "format": "hoch",
    "titelbild": "images/platzhalter/projekt-07-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-07-a.jpg",
      "images/platzhalter/projekt-07-b.jpg",
      "images/platzhalter/projekt-07-c.jpg"
    ]
  },
  {
    "id": "projekt-08",
    "projekt": "Projekt 08",
    "massstab": "1:100",
    "kunde": "Architekturbüro Muster",
    "format": "quer",
    "titelbild": "images/platzhalter/projekt-08-titel.jpg",
    "weitereBilder": [
      "images/platzhalter/projekt-08-a.jpg",
      "images/platzhalter/projekt-08-b.jpg",
      "images/platzhalter/projekt-08-c.jpg"
    ]
  }
];

window.PROJEKTE = PROJEKTE;
